name: Autopep8 Check

on: [push, pull_request]

jobs:
  Autopep8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint
      run: |
        pylint hw2/hw2_debugging.py hw2/rand.py | tee pylint_trace-report.txt
        if [ -s pylint_trace-report.txt ]; then
            echo "status=fail" >> $GITHUB_ENV
        else
          echo "status=pass" >> $GITHUB_ENV
        fi