name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
   
    - name: Run tests with coverage
      run: |
          pytest --cov=./
    - name: Generate coverage badge
      run: coverage-badge -o coverage.svg -f

    - name: Commit coverage badge
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add coverage.svg
        git commit -m "Add coverage badge"
        git push
